# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-10 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='作者')),
            ],
            options={
                'verbose_name': '文章作者表',
                'verbose_name_plural': '文章作者表',
            },
        ),
        migrations.CreateModel(
            name='NewsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('description', models.TextField(verbose_name='文章描述')),
                ('content', models.TextField(null=True, verbose_name='文章内容')),
                ('pic', models.ImageField(default='news/default_300x300.jpg', max_length=200, upload_to='news/', verbose_name='文章缩略图')),
                ('url', models.CharField(max_length=100, verbose_name='文章源地址')),
                ('make_time', models.CharField(blank=True, max_length=20, null=True, verbose_name='上传时间')),
                ('pub_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='入库时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.NewsAuthor', verbose_name='文章作者')),
                ('tag', models.ManyToManyField(blank=True, to='videos.Tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '机情快讯列表',
                'verbose_name_plural': '机情快讯列表',
            },
        ),
    ]
