# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-18 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20190818_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslist',
            name='aid',
            field=models.IntegerField(null=True, verbose_name='文章ID'),
        ),
        migrations.AlterField(
            model_name='newslist',
            name='content',
            field=models.TextField(null=True, verbose_name='文章内容'),
        ),
    ]
