# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-18 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20190818_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslist',
            name='make_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='上传时间'),
        ),
    ]
