# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-18 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20190818_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslist',
            name='make_time',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='上传时间'),
        ),
    ]
