# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-19 06:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20190818_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newslist',
            name='aid',
        ),
    ]
