# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-13 15:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190812_2157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': '用户表', 'verbose_name_plural': '用户表'},
        ),
    ]
