# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-13 15:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190813_2342'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id'], 'verbose_name': '用户表', 'verbose_name_plural': '用户表'},
        ),
    ]
