# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-25 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_avator_sm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avator_sm',
            field=models.ImageField(default='avator/20190816/default.jpg', upload_to='avator/%Y%m%d/', verbose_name='头像缩略图'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avator_sor',
            field=models.ImageField(default='avator/20190816/default.jpg', upload_to='avator/%Y%m%d/', verbose_name='头像'),
        ),
    ]
