# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-10 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicParams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu', models.CharField(blank=True, max_length=50, null=True, verbose_name='CPU')),
                ('back', models.CharField(blank=True, max_length=100, null=True, verbose_name='后置')),
                ('front', models.CharField(blank=True, max_length=50, null=True, verbose_name='前置')),
                ('memory', models.CharField(blank=True, max_length=50, null=True, verbose_name='内存')),
                ('battery', models.CharField(blank=True, max_length=50, null=True, verbose_name='电池')),
                ('screen', models.CharField(blank=True, max_length=50, null=True, verbose_name='屏幕')),
                ('dpi', models.CharField(blank=True, max_length=50, null=True, verbose_name='分辨率')),
            ],
            options={
                'verbose_name': '手机基本参数表',
                'verbose_name_plural': '手机基本参数表',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.CharField(blank=True, default='0.0', max_length=5, null=True, verbose_name='总评分')),
                ('xjb', models.CharField(blank=True, default='0.0', max_length=5, null=True, verbose_name='性价比')),
                ('xn', models.CharField(blank=True, default='0.0', max_length=5, null=True, verbose_name='性能')),
                ('xh', models.CharField(blank=True, default='0.0', max_length=5, null=True, verbose_name='续航')),
                ('wg', models.CharField(blank=True, default='0.0', max_length=5, null=True, verbose_name='外观')),
                ('pz', models.CharField(blank=True, default='0.0', max_length=5, null=True, verbose_name='拍照')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='对应机型')),
            ],
            options={
                'verbose_name': 'ZOL网友评分表',
                'verbose_name_plural': 'ZOL网友评分表',
            },
        ),
        migrations.CreateModel(
            name='Params',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic', models.TextField(blank=True, null=True, verbose_name='基本参数')),
                ('screen', models.TextField(blank=True, null=True, verbose_name='屏幕')),
                ('hardware', models.TextField(blank=True, null=True, verbose_name='硬件')),
                ('net', models.TextField(blank=True, null=True, verbose_name='网络与连接')),
                ('camera', models.TextField(blank=True, null=True, verbose_name='摄像头')),
                ('appearance', models.TextField(blank=True, null=True, verbose_name='外观')),
                ('function', models.TextField(blank=True, null=True, verbose_name='功能与服务')),
                ('pack', models.TextField(blank=True, null=True, verbose_name='手机附件')),
                ('protect', models.TextField(blank=True, null=True, verbose_name='保修信息')),
            ],
            options={
                'verbose_name': '手机详细参数表',
                'verbose_name_plural': '手机详细参数表',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='品牌名称')),
                ('pic_path', models.CharField(default='info/images/brand/default.jpg', max_length=100, verbose_name='品牌logo图')),
                ('office_url', models.CharField(max_length=100, null=True, verbose_name='官方网站')),
            ],
            options={
                'verbose_name': '手机品牌表',
                'verbose_name_plural': '手机品牌表',
            },
        ),
        migrations.CreateModel(
            name='PhoneModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, verbose_name='手机型号')),
                ('product_date', models.DateField(blank=True, null=True, verbose_name='上市日期')),
                ('price', models.CharField(default='暂无报价', max_length=10, verbose_name='ZOL报价')),
                ('hot_rank', models.IntegerField(blank=True, null=True, verbose_name='热门排行榜')),
                ('jd_url', models.CharField(default='https://www.jd.com', max_length=100, verbose_name='京东入口')),
                ('jd_price', models.CharField(default='暂无报价', max_length=10, verbose_name='京东报价')),
                ('jd_goodrate', models.CharField(default='暂无数据', max_length=10, verbose_name='京东好评率')),
                ('sn_goodrate', models.CharField(default='暂无数据', max_length=10, verbose_name='苏宁好评率')),
                ('description', models.TextField(verbose_name='信息简述')),
                ('img', models.ImageField(default='phones/default.jpg', upload_to='media/phones/', verbose_name='手机缩略图')),
                ('bimg', models.ImageField(default='phone_img/default.jpg', upload_to='media/phone_img/', verbose_name='展示图')),
                ('basicparams', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='phone', to='info.BasicParams', verbose_name='手机基本参数')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Phone', verbose_name='所属品牌')),
                ('params', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='info.Params', verbose_name='手机详细参数')),
                ('score', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info.Comment', verbose_name='网友评分')),
            ],
            options={
                'verbose_name': '手机信息表',
                'verbose_name_plural': '手机信息表',
            },
        ),
    ]
