# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-12 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Params',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='参数分类')),
            ],
            options={
                'verbose_name': '参数分类表',
                'verbose_name_plural': '参数分类表',
            },
        ),
        migrations.CreateModel(
            name='Params1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='参数项目')),
                ('clarification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Params', verbose_name='参数分类')),
            ],
            options={
                'verbose_name': '参数项目表',
                'verbose_name_plural': '参数项目表',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='品牌名称')),
            ],
            options={
                'verbose_name': '手机品牌',
                'verbose_name_plural': '手机品牌',
            },
        ),
        migrations.CreateModel(
            name='PhoneModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50, verbose_name='手机型号')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Phone', verbose_name='所属品牌')),
            ],
            options={
                'verbose_name': '手机品牌',
                'verbose_name_plural': '手机品牌',
            },
        ),
    ]
