# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-12 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_time', models.DateField(verbose_name='上市日期')),
            ],
            options={
                'verbose_name': '基本参数表',
                'verbose_name_plural': '基本参数表',
            },
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_type', models.CharField(max_length=200, verbose_name='触摸屏类型')),
            ],
            options={
                'verbose_name': '屏幕参数表',
                'verbose_name_plural': '屏幕参数表',
            },
        ),
        migrations.RemoveField(
            model_name='params1',
            name='clarification',
        ),
        migrations.AlterModelOptions(
            name='phone',
            options={'verbose_name': '手机品牌表', 'verbose_name_plural': '手机品牌表'},
        ),
        migrations.AlterModelOptions(
            name='phonemodel',
            options={'verbose_name': '手机详细参数表', 'verbose_name_plural': '手机详细参数表'},
        ),
        migrations.DeleteModel(
            name='Params',
        ),
        migrations.DeleteModel(
            name='Params1',
        ),
        migrations.AddField(
            model_name='phonemodel',
            name='basic',
            field=models.ManyToManyField(to='info.Basic', verbose_name='基本参数'),
        ),
        migrations.AddField(
            model_name='phonemodel',
            name='screen',
            field=models.ManyToManyField(to='info.Screen', verbose_name='屏幕'),
        ),
    ]
