# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-12 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20190812_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Params',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '手机详细参数表',
                'verbose_name_plural': '手机详细参数表',
            },
        ),
        migrations.AlterModelOptions(
            name='phonemodel',
            options={'verbose_name': '手机信息表', 'verbose_name_plural': '手机信息表'},
        ),
        migrations.RemoveField(
            model_name='phonemodel',
            name='basic',
        ),
        migrations.RemoveField(
            model_name='phonemodel',
            name='screen',
        ),
        migrations.AddField(
            model_name='basic',
            name='color',
            field=models.TextField(default='', verbose_name='机身颜色'),
        ),
        migrations.AddField(
            model_name='basic',
            name='cpu',
            field=models.TextField(default='', verbose_name='CPU型号'),
        ),
        migrations.AddField(
            model_name='basic',
            name='os',
            field=models.TextField(default='', verbose_name='操作系统'),
        ),
        migrations.AddField(
            model_name='basic',
            name='screen_type',
            field=models.TextField(default='', verbose_name='屏幕类型'),
        ),
        migrations.AddField(
            model_name='basic',
            name='system_kernel',
            field=models.TextField(default='', verbose_name='出厂系统内核'),
        ),
        migrations.AddField(
            model_name='basic',
            name='unlock_way',
            field=models.TextField(default='', verbose_name='解锁方式'),
        ),
        migrations.AlterField(
            model_name='basic',
            name='phone_type',
            field=models.TextField(default='', verbose_name='手机类型'),
        ),
        migrations.AddField(
            model_name='params',
            name='basic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='info.Basic', verbose_name='基本参数'),
        ),
        migrations.AddField(
            model_name='params',
            name='screen',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='info.Screen', verbose_name='屏幕'),
        ),
        migrations.AddField(
            model_name='phonemodel',
            name='params',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='info.Params', verbose_name='手机详细参数'),
            preserve_default=False,
        ),
    ]
