# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-15 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_auto_20190814_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicparams',
            name='back',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='后置'),
        ),
        migrations.AlterField(
            model_name='basicparams',
            name='battery',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='电池'),
        ),
        migrations.AlterField(
            model_name='basicparams',
            name='cpu',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CPU'),
        ),
        migrations.AlterField(
            model_name='basicparams',
            name='dpi',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='分辨率'),
        ),
        migrations.AlterField(
            model_name='basicparams',
            name='front',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='前置'),
        ),
        migrations.AlterField(
            model_name='basicparams',
            name='memory',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='内存'),
        ),
        migrations.AlterField(
            model_name='basicparams',
            name='screen',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='屏幕'),
        ),
        migrations.AlterField(
            model_name='params',
            name='appearance',
            field=models.TextField(blank=True, null=True, verbose_name='外观'),
        ),
        migrations.AlterField(
            model_name='params',
            name='basic',
            field=models.TextField(blank=True, null=True, verbose_name='基本参数'),
        ),
        migrations.AlterField(
            model_name='params',
            name='camera',
            field=models.TextField(blank=True, null=True, verbose_name='摄像头'),
        ),
        migrations.AlterField(
            model_name='params',
            name='function',
            field=models.TextField(blank=True, null=True, verbose_name='功能与服务'),
        ),
        migrations.AlterField(
            model_name='params',
            name='hardware',
            field=models.TextField(blank=True, null=True, verbose_name='硬件'),
        ),
        migrations.AlterField(
            model_name='params',
            name='net',
            field=models.TextField(blank=True, null=True, verbose_name='网络与连接'),
        ),
        migrations.AlterField(
            model_name='params',
            name='pack',
            field=models.TextField(blank=True, null=True, verbose_name='手机附件'),
        ),
        migrations.AlterField(
            model_name='params',
            name='protect',
            field=models.TextField(blank=True, null=True, verbose_name='保修信息'),
        ),
        migrations.AlterField(
            model_name='params',
            name='screen',
            field=models.TextField(blank=True, null=True, verbose_name='屏幕'),
        ),
    ]
