# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-20 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_auto_20190815_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='pic_path',
            field=models.CharField(default='info/images/brand/default.jpg', max_length=100, verbose_name='品牌logo图'),
        ),
    ]
