# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-20 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_phone_pic_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonemodel',
            name='description',
            field=models.TextField(default='无', verbose_name='信息简述'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phonemodel',
            name='price',
            field=models.CharField(default='暂无报价', max_length=10, verbose_name='ZOL报价'),
        ),
    ]
