# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-21 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0012_auto_20190821_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='total_score',
            field=models.CharField(blank=True, default='0.0', max_length=5, null=True, verbose_name='总评分'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pz',
            field=models.CharField(blank=True, default='0.0', max_length=5, null=True, verbose_name='拍照'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='wg',
            field=models.CharField(blank=True, default='0.0', max_length=5, null=True, verbose_name='外观'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='xh',
            field=models.CharField(blank=True, default='0.0', max_length=5, null=True, verbose_name='续航'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='xjb',
            field=models.CharField(blank=True, default='0.0', max_length=5, null=True, verbose_name='性价比'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='xn',
            field=models.CharField(blank=True, default='0.0', max_length=5, null=True, verbose_name='性能'),
        ),
    ]
