# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-25 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0015_comment_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonemodel',
            name='product_date',
            field=models.DateField(blank=True, null=True, verbose_name='上市日期'),
        ),
    ]
