# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-25 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0016_phonemodel_product_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonemodel',
            name='hot_rank',
            field=models.IntegerField(blank=True, null=True, verbose_name='热门排行榜'),
        ),
    ]
