# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-25 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0017_phonemodel_hot_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='office_url',
            field=models.CharField(max_length=100, null=True, verbose_name='官方网站'),
        ),
    ]
