# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-10 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='作者')),
            ],
            options={
                'verbose_name': '视频作者表',
                'verbose_name_plural': '视频作者表',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='标签名')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.CreateModel(
            name='VideoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('aid', models.IntegerField(verbose_name='视频ID')),
                ('duration', models.CharField(max_length=6, verbose_name='视频时长')),
                ('pic', models.CharField(max_length=100, verbose_name='缩略图')),
                ('play', models.IntegerField(verbose_name='播放量')),
                ('url', models.CharField(max_length=100, verbose_name='视频源地址')),
                ('make_time', models.DateField(blank=True, null=True, verbose_name='上传时间')),
                ('pub_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='入库时间')),
                ('img', models.ImageField(default='video/default_300x300.jpg', upload_to='video/', verbose_name='视频缩略图')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.Author', verbose_name='视频作者')),
                ('tag', models.ManyToManyField(blank=True, to='videos.Tag', verbose_name='视频标签')),
            ],
            options={
                'verbose_name': '视频列表',
                'verbose_name_plural': '视频列表',
            },
        ),
    ]
