# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-15 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videolist',
            name='aid',
            field=models.IntegerField(verbose_name='视频ID'),
        ),
        migrations.AlterField(
            model_name='videolist',
            name='play',
            field=models.IntegerField(verbose_name='播放量'),
        ),
    ]
